APP_NAME = "Log Retriever v1.0"

INPUT_VALID_ASIIGNER = "="
MANDATORY_PARAMETER_INPUT = "--input"
MANDATORY_PARAMETER_OUTPUT = "--output"

LOG_PATH = 'logs/'
LOG_MAXBYTES = 5242880 #1024*1024*5 bytes
LOG_BACKUPCOUNT = 5
LOG_NAME = 'retriever.log'
